USE master;

DROP DATABASE IF EXISTS LAB13_1

CREATE DATABASE LAB13_1 ON(
    NAME=LAB13_1DB,
    FILENAME='/var/opt/mssql/data/lab13_1bd.mdf',
    SIZE=10,
    MAXSIZE=UNLIMITED,
    FILEGROWTH=5%
)
LOG ON(
    NAME=LAB13_1LOG,
    FILENAME='/var/opt/mssql/data/lab13_1log.ldf',
    SIZE=5MB,
    MAXSIZE=25MB,
    FILEGROWTH=5MB
)

DROP DATABASE IF EXISTS LAB13_2

CREATE DATABASE LAB13_2 ON(
    NAME=LAB13_2DB,
    FILENAME='/var/opt/mssql/data/lab13_2bd.mdf',
    SIZE=10,
    MAXSIZE=UNLIMITED,
    FILEGROWTH=5%
)
LOG ON(
    NAME=LAB13_2LOG,
    FILENAME='/var/opt/mssql/data/lab13_2log.ldf',
    SIZE=5MB,
    MAXSIZE=25MB,
    FILEGROWTH=5MB
)
GO

USE LAB13_1

DROP TABLE IF EXISTS Shop

CREATE TABLE Shop(
    id INT PRIMARY KEY NOT NULL,
    name NVARCHAR(25) NOT NULL,
    address NVARCHAR(50) NOT NULL,
    CONSTRAINT c CHECK (id<=5)
)
GO

USE LAB13_2

DROP TABLE IF EXISTS Shop

CREATE TABLE Shop(
    id INT PRIMARY KEY NOT NULL,
    name NVARCHAR(25) NOT NULL,
    address NVARCHAR(50) NOT NULL,
    CONSTRAINT c CHECK (id>5)
)
GO

USE LAB13_1

DROP VIEW IF EXISTS ShopView

GO

CREATE VIEW ShopView AS
SELECT * FROM LAB13_1.dbo.Shop
UNION ALL
SELECT * FROM LAB13_2.dbo.Shop

GO


USE LAB13_2

DROP VIEW IF EXISTS ShopView

GO

CREATE VIEW ShopView AS
SELECT * FROM LAB13_1.dbo.Shop
UNION ALL
SELECT * FROM LAB13_2.dbo.Shop

GO

INSERT INTO ShopView VALUES
(1,'FIRST','MOSCOW'),
(6,'SECOND','MOSCOW'),
(2,'GG','SMOLENSK'),
(7,'FF','MINSK')
GO


CREATE PROCEDURE listStaff AS
BEGIN
    SELECT * FROM ShopView

    SELECT * FROM LAB13_1.dbo.Shop
    SELECT * FROM LAB13_2.dbo.Shop
END
GO

EXECUTE listStaff
GO

DELETE FROM ShopView WHERE id=1

EXECUTE listStaff
GO

UPDATE ShopView SET name='UPDATED' WHERE name='SECOND'
EXECUTE listStaff