USE master;
GO

DROP DATABASE IF EXISTS LAB6

CREATE DATABASE LAB6 ON(
    NAME=LAB6DB,
    FILENAME='/var/opt/mssql/data/lab6bd.mdf',
    SIZE=10,
    MAXSIZE=UNLIMITED,
    FILEGROWTH=5%
)
LOG ON(
    NAME=LAB6LOG,
    FILENAME='/var/opt/mssql/data/lab6log.ldf',
    SIZE=5MB,
    MAXSIZE=25MB,
    FILEGROWTH=5MB
)
GO

-------
USE LAB6;

DROP TABLE IF EXISTS HotelRoom

CREATE TABLE HotelRoom(
    Room_Number INT IDENTITY(1,1) PRIMARY KEY,
    Capacity INT NOT NULL CHECK(Capacity>0), 
    Is_Empty NVARCHAR(3) NOT NULL DEFAULT('YES'),
    "Check-in_time" DATE,
    "Check-out_time" DATE,
    CONSTRAINT checkInOutTime 
    CHECK (Is_Empty='YES' OR ("Check-in_time" IS NOT NULL AND "Check-out_time" IS NOT NULL AND "Check-in_time"<"Check-out_time"))
)

GO

INSERT INTO HotelRoom(Capacity,Is_Empty,[Check-in_time],[Check-out_time]) VALUES
(2,'YES',null,null),
(2,'NO',CAST('2020-05-08' AS DATE),CAST('2020-05-20' AS DATE))
-- (4,'YES',CAST('2020-05-08' AS DATE),CAST('2020-03-20' AS DATE)) ERROR 
-- (4,'NO',NULL,NULL) ERROR
INSERT INTO HotelRoom(Capacity) VALUES (2),(3),(4)

GO
-------

DROP TABLE IF EXISTS Hotel

CREATE TABLE Hotel(
    Hotel_Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT(NEWID()),
    Name NVARCHAR(20) NOT NULL,
    Stars TINYINT NOT NULL CHECK(Stars>1),
)

INSERT INTO Hotel(Name,Stars) VALUES
('Blue Ocean',5),('SunRise',5),('Sunshine',4)

GO
-------

DROP SEQUENCE IF EXISTS Id_Sequence 

CREATE SEQUENCE Id_Sequence 
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 50

DROP TABLE IF EXISTS PhoneBook

CREATE TABLE PhoneBook(
    Record_Number INT PRIMARY KEY,
    Phone_Number VARCHAR(11) NOT NULL,
    Comments NVARCHAR,
)

INSERT INTO PhoneBook(Record_Number,Phone_Number) VALUES
(NEXT VALUE FOR dbo.Id_Sequence,'79771234251'),
(NEXT VALUE FOR dbo.Id_Sequence,'79771234252'),
(NEXT VALUE FOR dbo.Id_Sequence,'79771234253')

GO
-------

DROP TABLE IF EXISTS Shop

CREATE TABLE Shop(
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Shop_Name NVARCHAR(20) NOT NULL UNIQUE DEFAULT(N'Дикси'),
)

DROP TABLE IF EXISTS Product

CREATE TABLE Product(
    Product_Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT(NEWID()),
    Name NVARCHAR(20) NOT NULL DEFAULT(N'Первым делом'),
    Price INT NOT NULL,
    Shop_Id INT,
    CONSTRAINT Shop_FK FOREIGN KEY (Shop_Id) REFERENCES Shop(Id)
    -- ON UPDATE CASCADE
    ON DELETE SET NULL
    --ON DELETE NO ACTION
    --ON DELETE SET DEFAULT
    -- ON UPDATE SET NULL
    -- ON UPDATE NO ACTION
    -- ON UPDATE SET DEFAULT
    --ON DELETE CASCADE
)

INSERT INTO Shop(Shop_Name) VALUES 
(N'Перекресток'),(N'Пятерочка'),(N'Верный'),(N'Магнолия')

SELECT SCOPE_IDENTITY() as id--This function will return the value of the last identity inserted in the current executing batch.
SELECT IDENT_CURRENT('dbo.Shop') as id--This function returns the last identity value inserted in the specified table, regardless of the scope and connection.
SELECT @@IDENTITY as id-- This variable contains the last identity value generated by the current connection

INSERT INTO Product(Name,Price,Shop_Id) VALUES 
(N'Сок Добрый',100,1),('Twix',45,1),(N'Аква Минерале',40,2),('Chester',100,3),(N'Молодой Мельник',80,4),(N'Молоко Простоквашино',70,1)

GO

DELETE FROM Shop WHERE Id=1
SELECT * FROM Shop
SELECT * FROM Product 

SELECT * FROM Shop