USE LAB6
GO

-- SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
-- BEGIN TRANSACTION
-- SELECT * FROM BankAccount
-- SELECT * FROM sys.dm_tran_locks
-- COMMIT TRANSACTION
-- GO

-- SET TRANSACTION ISOLATION LEVEL READ COMMITTED
-- BEGIN TRANSACTION
--     SELECT * FROM BankAccount
--     WAITFOR DELAY '00:00:05'
--     SELECT * FROM BankAccount
--     SELECT * FROM sys.dm_tran_locks
-- COMMIT TRANSACTION;
-- GO

-- SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
-- BEGIN TRANSACTION
--     SELECT * FROM BankAccount  
--     WAITFOR DELAY '00:00:05'  
--     SELECT * FROM BankAccount
--     SELECT * FROM sys.dm_tran_locks;
-- COMMIT TRANSACTION
-- GO

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRANSACTION
    SELECT * FROM BankAccount 
    WAITFOR DELAY '00:00:05'  
    SELECT * FROM BankAccount
    SELECT * FROM sys.dm_tran_locks
COMMIT TRANSACTION
GO