USE master;
GO

IF DB_ID(N'LAB5') IS NOT NULL DROP DATABASE LAB5

CREATE DATABASE LAB5 ON(
    NAME=LAB5DB,
    FILENAME='/var/opt/mssql/data/lab5bd.mdf',
    SIZE=10,
    MAXSIZE=UNLIMITED,
    FILEGROWTH=5%
)
LOG ON(
    NAME=LAB5LOG,
    FILENAME='/var/opt/mssql/data/lab5log.ldf',
    SIZE=5MB,
    MAXSIZE=25MB,
    FILEGROWTH=5MB
)
GO

USE LAB5;
GO

IF OBJECT_ID(N'Person') IS NOT NULL DROP TABLE Person

CREATE TABLE Person(
    FirstName varchar(20),
    SecondName VARCHAR(20),
    Address VARCHAR(80)
)

INSERT INTO Person(FirstName,SecondName,Address) VALUES ('Vladislav','Muryzhnikov','Moscow')
GO

USE master;
ALTER DATABASE LAB5 ADD FILEGROUP LAB5FG
GO
ALTER DATABASE LAB5 ADD FILE(
    NAME=test,
    FILENAME='/var/opt/mssql/test.ndf',
    SIZE=10MB,
    MAXSIZE=25MB,
    FILEGROWTH=5MB
) TO FILEGROUP LAB5FG
GO
ALTER DATABASE LAB5 MODIFY FILEGROUP LAB5FG DEFAULT;
GO

USE LAB5;
GO
IF OBJECT_ID(N'Car') IS NOT NULL DROP TABLE Car

CREATE TABLE Car(
    Colour VARCHAR(20),
    Brand VARCHAR(20)
)

INSERT INTO Car(Colour,Brand) VALUES ('Green','Toyota')
GO
ALTER DATABASE LAB5 MODIFY FILEGROUP [PRIMARY] DEFAULT;
GO

USE LAB5;
GO 
IF OBJECT_ID(N'db.Car') IS NOT NULL SELECT * INTO db.[dbo].Car FROM LAB5.[dbo].Car
DROP TABLE Car     

ALTER DATABASE LAB5 REMOVE FILE test
ALTER DATABASE LAB5 REMOVE FILEGROUP LAB5FG
GO

USE LAB5;
GO
CREATE SCHEMA SCM;
GO

ALTER SCHEMA SCM TRANSFER dbo.Person
DROP TABLE SCM.Person
DROP SCHEMA SCM
GO
